version: '3.8'

services:
  webapi:
    image: online-store-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "43754:80"
    depends_on:
      - sql-server
      - redis

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: Test1234
      ACCEPT_EULA: Y
    ports:
      - "1444:1433"

  redis:
    image: redis
    ports:
      - "6379:6379"
